### ISSUE TITLE
Armor render stuck on screen when using Oculus Shaders

### ISSUE THREAD

**Issue by AvrgDerk** [VeroxUniverse/EpicSamurai-1.19.2-forge#18]
I'm using Oculus 1.6.4 and I keep getting a 3d model of my armor that appears when looking at the sky or any space behind blocks, when using shaders. I've tested other armors in my modpack and only the samurai armor models seem to cause this issue. It follows me whenever I move but shifts position wildly. I really hope this can be fixed as this mod was one I looked forward to using the most with shaders ;-;

![image](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/44188778/95c9da9b-5268-4454-89c2-0825e9fd882b)
![image](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/44188778/7c65dd94-a3d2-41dd-a472-988abbf99c3b)

**Comment by VeroxUniverse** [comment]
I know geckolib and oculus will fix it soon.
