### ISSUE TITLE
Fabric release crash on startup

### ISSUE THREAD

**Issue by dmsw0303** [VeroxUniverse/EpicSamurai-1.19.2-forge#27]
Just wanted to thank you for the port, cant even explain how happy i was to see this pop up for fabric today. will say that i had some issues getting the game to start after adding to my modpack

heres the crash log: https://mclo.gs/khb1PSN

hopefully it can help. thank you again. really appreciate being able to use your art in my modpack

also sorry to use the forge repo, noticed you didnt have a fabric one yet and your comments were turned off. figured you wouldnt mind

**Comment by VeroxUniverse** [comment]
install AzureLib!
