### ISSUE TITLE
[bug] can not load world

### ISSUE THREAD

**Issue by Matej444444** [VeroxUniverse/EpicSamurai-1.19.2-forge#28]
Hi, i can not get any version to load any world. It just stops working. I tried using other version, but i still get that error. I'm using tlauncher's forge with optifine.
[Uploading latest.log…]()

**Comment by VeroxUniverse** [comment]
Dont use optfine with it. And Tlauncher is for cracked minecraft and I won't support cracked version sorry. Buy Minecraft and use Curseforge, Modrinth or ATLauncher.
