### ISSUE TITLE
[1.20.1]Unable to spawns monsters with mod TFC

### ISSUE THREAD

**Issue by Tollainmear** [VeroxUniverse/EpicSamurai-1.19.2-forge#33]
Hi, I've noticed that when this mod and the TerraFirmaCraft mod are loaded at the same time, no hostile mobs are being spawned in the overworld(TFC type). I've conducted a simple test; just having these two mods loaded together can reproduce the issue. Upon removing the EpicSamurai mod and restarting the game, hostile mobs begin to spawn. I think this issue should be fairly easy to replicate. So, if you have the time, could you please assess this problem? I really appreciate it. I am using the latest versions of the TFC and EpicSamurai mods on the Forge 47.2.20.

![image](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/25898067/ea974656-b39b-4bba-b517-0e4946569380)

**Comment by Tollainmear** [comment]
Hi, the problem was solved after I deleted the files in the `data/forge/tags/blocks/ores` folder and `data/forge/tags/blocks/ores.json` file within `epicsamurai.jar`.

I'm happy to share the solution with you, and I hope this can help you pinpoint where the problem originated.

I believe this still counts as a compatibility issue. Due to my lack of understanding of the data packet creation rules, I can only circumvent the problem by deleting the files. Obviously, this is not the best solution. Of course, if you think this issue is not significant, please feel free to close this issue. Thank you once again.

**Comment by alcatrazEscapee** [comment]
This is a bug in Epic Samurai's tag definitions, which just happens to affect TFC:

- TFC restricts mob spawning to only spawn on the tag [`#tfc:monster_spawns_on`](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.20.x/src/main/resources/data/tfc/tags/blocks/monster_spawns_on.json), which includes `#forge:ores`
- TFC adds `#forge:ores/amethyst` to `#forge:ores`.
- Epic Samurai adds `minecraft: ` to `#forge:ores/amethyst`, here: https://github.com/VeroxUniverse/EpicSamurai-forge/blob/9b2c9efceefa50c1dd1b6b05899e466f297c715f/src/main/resources/data/forge/tags/blocks/ores/amethyst.json#L3 This block **does not exist** in minecraft. This is an **item**, and should not be included in a block tag.

This bug becomes obvious when launching Epic Samurai, where the following errors are present in the log:

```
[13:55:48] [Worker-Main-15/ERROR] [minecraft/TagLoader]: Couldn't load tag eldritch_end:etyr_armor as it is missing following references: epicsamurai:etyrite_samurai_helmet (from epicsamurai-0.0.34.1-1.20.1-neo.jar), 
	epicsamurai:etyrite_samurai_chestplate (from epicsamurai-0.0.34.1-1.20.1-neo.jar), 
	epicsamurai:etyrite_samurai_leggings (from epicsamurai-0.0.34.1-1.20.1-neo.jar), 
	epicsamurai:etyrite_samurai_boots (from epicsamurai-0.0.34.1-1.20.1-neo.jar)
[13:55:48] [Worker-Main-7/ERROR] [minecraft/TagLoader]: Couldn't load tag forge:ores/amethyst as it is missing following references: minecraft:amethyst_shard (from epicsamurai-0.0.34.1-1.20.1-neo.jar)
[13:55:48] [Worker-Main-15/ERROR] [minecraft/TagLoader]: Couldn't load tag epicsamurai:dampens_vibrations as it is missing following references: epicsamurai:sculk_samurai_boots (from epicsamurai-0.0.34.1-1.20.1-neo.jar)
[13:55:48] [Worker-Main-15/ERROR] [minecraft/TagLoader]: Couldn't load tag deeperdarker:dampens_vibrations as it is missing following references: epicsamurai:sculk_samurai_boots (from epicsamurai-0.0.34.1-1.20.1-neo.jar)
```

Full log: https://paste.ee/p/Gbmj4

@Tollainmear you should be able to fix this by deleting just [this file](https://github.com/VeroxUniverse/EpicSamurai-forge/blob/1.20.1-forge/src/main/resources/data/forge/tags/blocks/ores/amethyst.json), without any other consequences.
