### ISSUE TITLE
Two-handed katana placement

### ISSUE THREAD

**Issue by NABS2ER** [VeroxUniverse/EpicSamurai-1.19.2-forge#36]
It's very awkward to play with the katana at the ready because for some reason it's pointed forward like a spear. All similar mods where there are two-handed weapons fit compactly and comfortably in the hand.
I wanted to change the angle of the katana myself, but I couldn’t find the config! Do you agree with me that this position of the katana is incorrect and uncomfortable? If so, could you make it like the other sword that I showed? 
![2024-03-01_11 37 01](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/141981213/9ad859f9-bcb0-4890-86dc-5bb0efbdb7c1)

This is also a two-handed katana, but from a different mod, for me it fits correctly and comfortably in the hand
![2024-03-01_11 37 08](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/141981213/55d936d6-5891-4dff-b939-22aeabab3e9d)

**Comment by NABS2ER** [comment]
Does this mean there will be no fix?
You should have written at least what you think about this, otherwise they closed it silently and that’s it

**Comment by VeroxUniverse** [comment]
there is nothing to fix. And I can't change everything because some players wanna have changes.

**Comment by NABS2ER** [comment]
Hello, the problem is still relevant, many updates have already passed, is it possible to include this problem in the next update? Is it really that hard to change the tilt of a sword in first person? This is not a spear that faces forward, all swords look up, but this one is directed forward!, wrong and inconvenient! Цell just trust me and fix it please...

**Comment by VeroxUniverse** [comment]
1.21 got all weapon changes and the rework.
You should know I have more than one project.
And how I've mentioned before I won't change it.
At the end it is my decision.

**Comment by NABS2ER** [comment]
Please duplicate the changes to 1.20.1

**Comment by VeroxUniverse** [comment]
No!

**Comment by NABS2ER** [comment]
Can I change this myself in the config and if so, tell me how!?

**Comment by VeroxUniverse** [comment]
The Katana in 1.21 has a different model. 
And you can create your own resource pack with the display settings you wanna have.
