### ISSUE TITLE
Oni/Kitsune Mask

### ISSUE THREAD

**Issue by MrHimera** [VeroxUniverse/EpicSamurai-1.19.2-forge#37]
Minecraft: 1.20.1
Forge: 47.2.20
Curios API: 5.7.0
AzureLib: 2.0.20
Epic Samurai's: 0.0.38

After update 0.0.38, Oni/Kitsune Mask items cannot be used.

**Comment by VeroxUniverse** [comment]
I hope it is fixed with the new update.
