### ISSUE TITLE
[1.20.1] - Tanuki disappears when placing into a seat from Create

### ISSUE THREAD

**Issue by ToxinZangoose** [VeroxUniverse/EpicSamurai-1.19.2-forge#38]
Hello,

This happened to a friend of mine that had been gifted a tanuki from me, he went to place the tanuki onto a seat and it appeared to have vanished from the world. He used Carry On to pick up the tanuki and the issue was caused after he placed it down.

If there's any way to resolve this in a future update, please look into it.

Thank you, I would provide a crash log or error log, but I'm on a server and cannot access the files for security reasons.

**Comment by VeroxUniverse** [comment]
I will have a look. I think it is because of the ability of the mob.
