### ISSUE TITLE
Kitsune Crashes Your Game Due To ANY Projectile

### ISSUE THREAD

**Issue by Cyranos** [VeroxUniverse/EpicSamurai-1.19.2-forge#4]
If you try and shoot a Kitsune with anything that fires a projectile, be it the Archangel's Smite from Project E Or the minigun attachment from Late Game Golems, IT WILL CRASH YOUR GAME.

Archangel's Smite Crash Log;
https://mclo.gs/7LzSVpc

Late Game Golem With A Magic Flame Thrower
https://mclo.gs/VfcK6Zi

Late Game Golem With A Minigun
https://mclo.gs/SyfDAvZ

**Comment by VeroxUniverse** [comment]
I will try to fix it today. I think I know whats the problem.

**Comment by jovi-tsx** [comment]
Not only crash your game, it gives you a ticking entity which obliges you to regenerate your world.
