### ISSUE TITLE
Steel Ingot with Create is bugged

### ISSUE THREAD

**Issue by AkuseruGH** [VeroxUniverse/EpicSamurai-1.19.2-forge#44]
iron ingot cant be blasted with blast furnace to get steel ingot
![image](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/106091430/b01905e4-93fa-4903-88bf-b1c8a5887b4f)
and its recipé doesn´t appear in JEI, only appears create recipe
![image](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/106091430/5ce7c0c9-645e-479d-bf23-2c8f49811b1f)

**Comment by VeroxUniverse** [comment]
That is intended

**Comment by VeroxUniverse** [comment]
The create recipe is by the mod. It changes if create is installed.
