### ISSUE TITLE
Change keys for special abilities

### ISSUE THREAD

**Issue by Icus7** [VeroxUniverse/EpicSamurai-1.19.2-forge#45]
I'm sorry I'm using a translation software, so please forgive me for any language inappropriateness.I would like to ask how to change the key of the special katana's right button use ability? Because it will make the epic battle block can not work properly, please ask me what to do, thank you!

**Comment by VeroxUniverse** [comment]
you cant

**Comment by VeroxUniverse** [comment]
The mod was not originally intended for use with epic fight
