### ISSUE TITLE
1.19.2 netherite armor.

### ISSUE THREAD

**Issue by gabbigamers** [VeroxUniverse/EpicSamurai-1.19.2-forge#46]
The netherite armor is completely textureless on 1.19.2.

**Comment by gabbigamers** [comment]
Nevermind all of them are textureless.

**Comment by gabbigamers** [comment]
after downgrading i realised it was just the latest version for 1.19.2

**Comment by VeroxUniverse** [comment]
dont use optfine with it

**Comment by gabbigamers** [comment]
I wasnt using optifine. I was using embeddium then i used rubidium and once i downgraded from latest to one version down, it started showing textures with both embeddium and rubidium.
