### ISSUE TITLE
Tag issues breaking other mods

### ISSUE THREAD

**Issue by ByThePowerOfScience** [VeroxUniverse/EpicSamurai-1.19.2-forge#49]
### Minimum reproducible example: 
1. Install [Embers Rekindled 1.20.1](https://www.curseforge.com/minecraft/mc-mods/embers-rekindled/files/5315565) alone.
2. In any world, place down a Dawnstone Anvil.
3. Right-click the anvil with any pickaxe, and then an Ancient Motive Core.
4. Right-click the anvil with a Tinkers Hammer. A particle should appear and a sound effect should play, indicating that the recipe is valid.
5. Repeat the above steps with Epic Samurai installed. The recipe is no longer valid.

After a few hours of narrowing down causes, I've found that this recipe is broken only when this mod is installed.  It seems that ES is doing something to one of the standard forge tags that results in other mods being unable to resolve their tags that depend on them.  

I'm investigating the issue on my own to patch it with ASM for a modpack, but I wanted to raise it here first.

**Comment by VeroxUniverse** [comment]
Can you send a log via pastebin?

**Comment by ByThePowerOfScience** [comment]
https://mclo.gs/cGge9kc

It might be this:
```
[22May2024 22:00:49.441] [Worker-Main-2/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:armors/helmets as it is missing following references: epicsamurai:mask_netherite_samurai_helmet (from epicsamurai-0.0.42-1.20.1-neo.jar), 
	epicsamurai:mask_amethyst_samurai_helmet (from epicsamurai-0.0.42-1.20.1-neo.jar), 
	epicsamurai:mask_quartz_samurai_helmet (from epicsamurai-0.0.42-1.20.1-neo.jar), 
	epicsamurai:mask_straw_hat (from epicsamurai-0.0.42-1.20.1-neo.jar)
```

I didn't realize the tag system was this brittle.  Apparently just lacking a single entry causes _every single dependent tag_ to become unresolvable.  Jeez.
