### ISSUE TITLE
Armor Names Bug

### ISSUE THREAD

**Issue by rafaelantunes04** [VeroxUniverse/EpicSamurai-1.19.2-forge#5]
**Versions**

Minecraft Version: 1.19.2
Forge Version: 43.2.0
Epic Samurai's Version: 0.0.13
Curius API Version: 5.1.4.1
GeckoLib Version: 3.1.40
Patchouli Version: 77

**The Bug**
Quartz armor name is bugged
![image](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/35634474/b623986c-1f68-4ff6-b30b-37b85b4f3561)

Amethyst armor is named Quartz Armor
![image](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/35634474/8b32f9d6-9de3-4736-8820-13985013b19b)

Oni mask name is bugged
![image](https://github.com/VeroxUniverse/EpicSamurai-forge/assets/35634474/52782aeb-df08-43a8-9f03-11ec754e3f4b)

**Comment by VeroxUniverse** [comment]
Its no bug. Its just a missing name. And I will work on some things for now.

**Comment by VeroxUniverse** [comment]
So it will be fixed with the next update. Because I have changed it some days before.
