### ISSUE TITLE
Structures missing blocks

### ISSUE THREAD

**Issue by grimmtastic** [VeroxUniverse/EpicSamurai-1.19.2-forge#52]
Structures are incomplete. I believe since the name change, some blocks are now missing(Spirit Bricks, statues, etc)
![2024-08-09_17 42 28](https://github.com/user-attachments/assets/7b30a469-b146-480c-aed9-716547ba8b8b)

**Comment by manzipan** [comment]
hello i have the same problem do you have a solution? for now i just downgrade one version and it seems to be ok.

**Comment by manzipan** [comment]
Thnx For the Update works perfectly now
