### ISSUE TITLE
Recipe Missing Errors

### ISSUE THREAD

**Issue by itsdeadfrosty** [VeroxUniverse/EpicSamurai-1.19.2-forge#54]
[latest.log](https://github.com/user-attachments/files/17606469/latest.log)

Error: Recipe not found warnings for multiple items (e.g., amethyst_ingot_smithing, stuffed_poblanos).
Impact: Incomplete or missing recipes for crafting items, possibly affecting gameplay progression.
Potential Conflict: Croptopia’s recipe issues appear frequently, which might indicate broader compatibility or registration issues.

**Comment by VeroxUniverse** [comment]
I tried to recreate it with only croptopia and samurai dynasty but I don't have this error.

**Comment by VeroxUniverse** [comment]
maybe some mods replacing the recipes? I know that modernfix or such can cause such issues. but I can take a look. Maybe I can find something.

**Comment by itsdeadfrosty** [comment]
anything helps, im trying to build a modpack and have it be stable for server use
