### ISSUE TITLE
1.21.1 Weapons & Armor cannot be enchanted

### ISSUE THREAD

**Issue by SkyRunner55** [VeroxUniverse/EpicSamurai-1.19.2-forge#55]
![image](https://github.com/user-attachments/assets/5df2c6e3-d78b-4a99-9b52-8287394d7f8c)
Nothing can be enchanted
I tried to put sharpness on the Netherite katana
I tried to put protection on the Netherite Samurai helmet

i know the mod just got out recently but in case
Mod version 0.1.1 1.21.1

**Comment by VeroxUniverse** [comment]
Hey thank you, I fixed it and will upload it soon

**Comment by aliceingame** [comment]
Did not want to open a new issue, but curious if the enchant selection intentionally did not include Mending for the armor and bow while it seems to be available on weapons.
