### ISSUE TITLE
[1.21.1 neoforge] Will upgraded katana will be added back ?

### ISSUE THREAD

**Issue by SkyRunner55** [VeroxUniverse/EpicSamurai-1.19.2-forge#58]
Back in 1.20.1 (or maybe older version too i don't know) you were able to upgrade your netherite katana to a katana with effects passive (Example give wither to target) and right click (speed when right click) and they had cool design
Is this feature is gonna be readded in minecraft 1.21.1 neoforge ?

**Comment by VeroxUniverse** [comment]
be patient. there are some reworks

**Comment by SkyRunner55** [comment]
> be patient. there are some reworks

ok
