### ISSUE TITLE
Bug Report: Samurai Dynasty Conflicts with Minecolonies

### ISSUE THREAD

**Issue by YumatanGames** [VeroxUniverse/EpicSamurai-1.19.2-forge#59]
## **Issue Description**
When using **Samurai Dynasty** (v0.1.2-1.21.1) alongside **Minecolonies** (v1.1.821-1.21.1-snapshot), the **Architect’s Cutter** from Minecolonies becomes unusable. This effectively breaks core functionality in Minecolonies, as the Architect’s Cutter is required to craft essential blocks for the mod.

---

## **Steps to Reproduce**
1. Install the following mods for Minecraft 1.21.1 with NeoForge:
   - **Minecolonies**: `minecolonies-1.1.821-1.21.1-snapshot.jar`
   - **Samurai Dynasty**: `samurai-dynasty-0.1.2-1.21.1.jar`
2. Create a new world (tested in **creative** mode).
3. Search for the **Architect’s Cutter** in the creative inventory and place it down.
4. Attempt to use the Architect’s Cutter:
   - Take any two blocks (e.g., planks, stone).
   - Try to craft any Minecolonies block using the cutter.

---

## **Observed Behavior**
The **Architect’s Cutter** does not accept any blocks as input, making it impossible to craft Minecolonies-required blocks.  
This issue occurs in both **creative** and **survival** modes.

---

## **Expected Behavior**
The **Architect’s Cutter** should allow players to insert blocks and craft required Minecolonies items.

---

## **Additional Notes**
- The issue disappears when **Samurai Dynasty** is removed, confirming it as the conflicting mod.
- Tested in an isolated environment with only Minecolonies and Samurai Dynasty installed.

---

## **Environment**
- **Minecraft Version:** 1.21.1
- **NeoForge Version:** Latest available for 1.21.1
- **Minecolonies Version:** `minecolonies-1.1.821-1.21.1-snapshot.jar`
- **Samurai Dynasty Version:** `samurai-dynasty-0.1.2-1.21.1.jar`

---

## **Suggested Priority**
This bug renders Minecolonies completely unusable when Samurai Dynasty is installed, which is unfortunate given the incredible synergy between the two mods. **Samurai Dynasty** enhances Minecolonies significantly for players building Japanese-style colonies by adding beautiful decorations, weapons, and armor that perfectly complement the theme. It would be a shame not to be able to combine these two mods when they work so well together conceptually.

**Comment by VeroxUniverse** [comment]
Hey it is a known issue will be fixed with the next major update
